os: osx
language: generic
before_install:
  - brew install terraform
  - brew install aliyun-cli
  - brew install python3
  - pip3 install pyyaml
deploy:
  provider: script
  script: sh scripts/deploy-destroy.sh
  on:
    branch: master
# in case of deploy/destroy failed, we run it again hoping to fix the resource leftover
after_deploy: sh scripts/clean.sh