apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-helm.fullname" . }}-service
  labels:
    {{- include "hello-helm.labels" . | nindent 4 }}
spec:
  externalTrafficPolicy: Cluster
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "hello-helm.selectorLabels" . | nindent 4 }}
