apiVersion: v1
kind: Service
metadata:
  name: demo06
  annotations:
    external-dns.alpha.kubernetes.io/hostname: demo06-service.yagr.xyz
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: demo06

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo06
spec:
  selector:
    matchLabels:
      app: demo06
  template:
    metadata:
      labels:
        app: demo06
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http